### PR TITLE
LGD lateral

### PR DESCRIPTION
**Pull request by mseibt**
This PR contains a LGD model including lateral interactions during diffusion.
It does **not** contain lateral interactions for the source_exit and drain_exit processes.

The conductivity plot takes ~3 times longer than for the model without lateral interactions.

### CODE REVIEW

**Comment by jmlorenzi** [comment]
Hi Michael,

Thank you very much for contributing this solution!
I have taken a look, and I think there is a small error: Some diffusion processes in which the source is a condition are repeated. This is equivalent to giving these processes a larger rate constant.

Are far as I see it, there are two ways of solving this:

a) Instead of adding the `diffusion_*_source` processes within the loop over `zip(names, delta_Es, coordinates)`, you could add them after the loop. (Only) once for each diffusion direction (up, right
and down).

b) Alternative, you could include the other conditions also in these processes. This way you could even also take into account the lateral interaction in these edge processes. Of course, what lateral interaction should be counted for the source is not clear... One should think how to model this, or simply treat the source as always empty (I guess it should not make much of a difference).

Am I making myself clear? Do you want to correct this? Else, I can do it later this week.

Best,
Juan

**Comment by mseibt** [comment]
Hi Juan,

thanks for your feedback!

I think you are right and I already tried to take approach a). However I created one more indentation than needed.
Do you think the last commit solves the problem?

Best regards,
Michael

**Comment by jmlorenzi** [comment]
Great. You solved the issue. But as I see it, you took approach b) now.

In case you are not aware: You can use the kmos editor to take a look at the processes in you model? This can be done with the command `kmos edit LGD_lateral.xml`.

Thank you once again for the contribution.
Best
Juan

**Comment by mseibt** [comment]
Yes - indeed it's approach b)!

Thanks for the hint with `kmos edit`. The graphical representation of the conditions / action is great!

Best regards,
Michael

**Pull request merged**
